<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
	<title>Xkeeper's Link's Awakening depot</title>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
	<style type="text/css">
	body	{
		background:		#ddd url('bg.png');
		font-family:	Verdana, sans-serif;
		color:			#000;
		font-size:		90%;
		text-align:		center;
		}
	div, h1, h2, h3	{
		text-align:		left;
		background:		#fff;
		border-bottom:	1px solid #777;
		border-right:	2px solid #aaa;
		padding:		2px 5px 2px 5px;
		max-width:		800px;
		margin-left:	auto;
		margin-right:	auto;
		margin-bottom:	2px;
		}
	h1, h2, h3	{
		text-align:		center;
		margin-top:	.5em;
		}
	ul	{
		margin-left:	none;
		list-style-type:	none;
		padding-left:		1em;
		}
	
	a:link		{	color:	#33f;	}
	a:visited	{	color:	#93f;	}
	.fr			{	float:	right;	font-size:	.75em;	}
	</style>
</head>
<body>

	<h1><a name="top">Xkeeper's Link's Awakening depot</a></h1>
	<div><div class="fr">[<a href="#top">#</a>]</div>

		<p>This is a page that acts as a sort of storage space for all the stuff I do with this game. Much thanks to <a href="http://artemis251.fobby.net/zelda.php">Artemis251</a>, who helped with the save data and has good (in-game) maps of the two underworlds.
		</p>

		<p>Navigation:		
		<ul>
			<li><a href="#saves">Save files</a></li>
			<li><a href="#tables">ROM table overlays</a></li>
			<li><a href="#maps">Maps</a></li>
			<li><a href="#rooms">Rooms</a></li>
		</ul>
	</div>

	
	<h2><a name="saves">Save Files</a></h2>
	<div><div class="fr">[<a href="#saves">#</a>] [<a href="#top">top</a>]</div>

		<p><a href="savedata.php">Save data output</a>: Uses a fairly recent LA:DX save and outputs the information in it as we understand it. Last updated with new information <?php print fdate("savedata.php"); ?>.
		</p>
		<p>Also included are maps showing room flags, which will be better understood eventually.
		</p>
	</div>

	<h2><a name="tables">ROM Table Overlays</a></h2>
	<div><div class="fr">[<a href="#tables">#</a>] [<a href="#top">top</a>]</div>
		<p><a href="chests.php">Chest mapping</a>: Reads from a table in ROM and overlays it onto a map of Koholint, showing what each screen will have in a chest. Also available in <a href="chests.php?m=1">Underworld 1</a> and <a href="chests.php?m=2">Underworld 2</a> flavors.
		</p>
	
		<p><a href="tileset.php">Tileset</a>: Overlays the tileset data for each 2x2 room set onto a map. Tilesets start at 1A and continue to 3E, with 0F meaning "keep current".
		</p>
	</div>

	
	<h2><a name="maps">Maps</a></h2>
	<div><div class="fr">[<a href="#maps">#</a>] [<a href="#top">top</a>]</div>
	
		<p><a href="drawermap0.png">Parsed map</a>: Latest map generated by my own room layout parser. Lots of things still aren't understood. Last updated <?php print fdate("drawermap0.png"); ?>.
		</p>
	
		<p>A few other maps may be coming eventually, provided the parser progresses.
		</p>
	</div>

	
	<h2><a name="rooms">Rooms</a></h2>
	<div><div class="fr">[<a href="#rooms">#</a>] [<a href="#top">top</a>]</div>
	
		<p><a href="render/">Room animations</a>: Shows a room being created in the order of the ROM's objects. Some are fairly interesting.
		</p>
	
		<p><a href="chestscreens.html">Chest screens</a>: Page showing screenshots of rooms that have chest data, but no chest; also included is a screenshot of opening a chest that was hacked into the room layout. Doesn't show all of the unused chests, but that might change. Last updated <?php print fdate("chestscreens.html"); ?>.
		</p>
	</div>

	<p><br></p>
	<div style="text-align: center;">Last update: <?php print fdate("index.php"); ?>
	<br>Made to be <a href="http://validator.w3.org/check?uri=referer">valid HTML 4.01 strict</a>.</div>

</body>
</html><?php

	function fdate($filename) {
		return date("m/d/Y", filemtime($filename));
	}
?>